#!/usr/bin/env node
// Build-boundary codegen: inline xr-widgets.wgsl as a normal TS string module so
// the renderer needs no bundler raw-import loader. [LAW:effects-at-boundaries] the
// only file I/O in the package lives here, at the build edge; the renderer stays a
// pure import. [LAW:one-source-of-truth] xr-widgets.wgsl is authoritative; the .gen.ts
// is a derived artifact, never hand-edited.
//
// Two modes, one generation rule so the two can never disagree:
//   (default)  write src/xr-widgets.wgsl.gen.ts from src/xr-widgets.wgsl
//   --check    regenerate in memory and fail loudly if the on-disk file drifted
//              [LAW:no-silent-failure] drift is the explicit synchronization that
//              [LAW:one-source-of-truth] demands of a committed derived artifact.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const SHADER_SRC = path.join(here, '..', 'src', 'xr-widgets.wgsl');
const GEN_OUT = path.join(here, '..', 'src', 'xr-widgets.wgsl.gen.ts');

// Pure: shader text -> generated module text. JSON.stringify yields a valid JS
// double-quoted string literal, so backticks/backslashes/newlines round-trip the
// shader byte-for-byte with no hand-rolled escaping.
function renderModule(shaderText) {
  return [
    '// GENERATED by packages/xr-ui/scripts/gen-shader.mjs — DO NOT EDIT.',
    '// Source of truth: ./xr-widgets.wgsl. Regenerate: npm run codegen -w @shader-playground/xr-ui',
    `export default ${JSON.stringify(shaderText)};`,
    '',
  ].join('\n');
}

const shaderText = fs.readFileSync(SHADER_SRC, 'utf8');
const expected = renderModule(shaderText);

if (process.argv.includes('--check')) {
  const actual = fs.existsSync(GEN_OUT) ? fs.readFileSync(GEN_OUT, 'utf8') : null;
  if (actual !== expected) {
    const reason = actual === null ? 'missing' : 'out of sync with xr-widgets.wgsl';
    console.error(`xr-widgets.wgsl.gen.ts is ${reason}. Run: npm run codegen -w @shader-playground/xr-ui`);
    process.exit(1);
  }
  console.log('xr-widgets.wgsl.gen.ts is in sync with xr-widgets.wgsl');
} else {
  fs.writeFileSync(GEN_OUT, expected);
  console.log(`Wrote ${path.relative(path.join(here, '..', '..', '..'), GEN_OUT)} (${shaderText.length} chars)`);
}
